Data:
  train_path: 'data/train/train'
  test_path: 'data/test/test'
  label_path: 'data/labels.csv'
  shuffle: True
  train_samples: 10
  test_samples: 10

Optimization:
  epochs: 10
  batch_size: 32
  lr: 0.001
