Data:
  dataset: 'data/ImageFolder'
  batch_size: 512
  train_size_ratio: 0.8

Train:
  model: 'mobile_net_v3'
  epochs: 30
  lr: 0.001
  weight_decay: 0.0001
  checkpoint_dir: 'checkpoints/mobile_net_v3'