Data:
  train_dataset: 'data/ImageFolder'
  infer_dataset: 'data/test'
  batch_size: 64
  train_size_ratio: 0.8

Train:
  model: 'eva02'
  epochs: 6
  lr: 0.001
  weight_decay: 0.01
  checkpoint_dir: 'checkpoints/eva02'

Test:
  checkpoint_path: 'checkpoints/model_final.ckpt'
  inference: False