Data:
  train_dataset: 'data/ImageFolder'
  infer_dataset: 'data/test'
  batch_size: 64
  train_size_ratio: 0.8

Train:
  model: 'resnet50'
  epochs: 30
  lr: 0.001
  weight_decay: 0.0001
  checkpoint_dir: 'checkpoints/resnet50'

Test:
  checkpoint_path: 'checkpoints/model_final.ckpt'
  validate_only: True
  inference_only: False